### ISSUE TITLE
Strange issue with inter-action processing of events

### ISSUE THREAD

**Issue by dingari** [boost-ext/sml#457] opened 2021-05-12 15:28 UTC
I'm facing a very peculiar problem in my program. We've been developing on macOS (Clang / GCC) for some while now and just tried building and running the code on Windows using MSVC.

* SML version: 1.1.4
* OS: Windows 10
* MSVC version: 19.28.29914 for x64

We have a case where we need to post/process an event directly from within an action in our FSM. Fortunately, boost::sml supports this through process queues. Taking inspiration from [this post](https://stackoverflow.com/a/58532272/14394243) we're able to successfully do that - at least on macOS.

Running the exact same code crashes on Windows. Digging down, I've only been able to replicate the issue if the posted event exceeds a certain size (16 bytes in this instance).

I've compiled the smallest example I can think of, it's available [here](https://godbolt.org/z/xj5aavK3j) (unfortunately Compiler Explorer does not support running code compiled with MSVC yet). I'll include the code here for context as well:

```
#include <iostream>
#include <queue>
#include <array>
#include <cassert>

#include <https://raw.githubusercontent.com/boost-experimental/sml/master/include/boost/sml.hpp>

int main() {
    namespace sml = boost::sml;

    class s1;
    class s2;

    struct e1 { char c; };
    struct e2 { std::array<char, 32> data{}; }; // The size of the data contained within seems to have an effect
                                                // Anything below 16 is fine and the FSM ends in the correct state
                                                // Anything between 17-24 causes the FSM to end in an incorrect state
                                                // Anything Above 24 will cause the program to crash

    struct table {
        auto operator()() const noexcept {
            using namespace sml;
            return make_transition_table(
                    * state<s1> + event<e1> / [](const e1& e, sml::back::process<e2> process) { process(e2{{e.c}}); } = state<s2>
                    , state<s2> + event<e2> = X

                    , state<s1> + sml::on_entry<_> / [] { std::cout << "s1 on entry" << std::endl; }
                    , state<s2> + sml::on_entry<_> / [] { std::cout << "s2 on entry" << std::endl; }
                    , state<s1> + sml::on_exit<_>  / [] { std::cout << "s1 on exit"  << std::endl; }
                    , state<s2> + sml::on_exit<_>  / [] { std::cout << "s2 on exit"  << std::endl; }
            );
        };
    };

    std::cout << "sizeof(e2): " <<  sizeof(e2) << "\n\n";

    // sml::process_queue is for post event
    sml::sm<table, sml::process_queue<std::queue>> sm;
    sm.process_event(e1{42});

    assert(sm.is(sml::X));
}
```

Here is an example output from three test runs with varying event sizes that I ran on my machine:

```
sizeof(e2): 16

s1 on entry
s1 on exit
s2 on entry
s2 on exit

Process finished with exit code 0

=======================================================

sizeof(e2): 24

s1 on entry
s1 on exit
s2 on entry
s2 on entry
Assertion failed: sm.is(sml::X), file ..\simple_test.cpp, line 40

Process finished with exit code 3

=======================================================

sizeof(e2): 32

s1 on entry
s1 on exit

Process finished with exit code -1073741819 (0xC0000005)
```

Note that in the second run the FSM seems to enter the `s2` state twice.

Oh and p.s. if I remove the `sml::on_exit<_>` statements (lines 29-30) the program runs fine with whatever size of `e2` 🤷  

If I could get some input on this that would be very helpful. Is there some sort of undefined behavior we're invoking here? Is there a better way to achieve the same goal?

For context:
* In my program it's crashing on [line 626](https://github.com/boost-ext/sml/blob/master/include/boost/sml.hpp#L626) in sml.hpp.
* In this test program it crashes on [line 645](https://github.com/boost-ext/sml/blob/master/include/boost/sml.hpp#L645) in sml.hpp

**Comment by dingari** [comment] 2021-05-20 11:53
I'm still scratching my head over this one. Do you have any idea why this could be behaving this way @krzysztof-jusiak?

**Comment by dingari** [comment] 2021-09-13 10:24
Is there a general issue with calling `process` directly from within an action? Is there some potential for undefined behaviour? 

I'm asking because we ran into some more random crashes (this time on macOS as well) that went away after removing all code that was calling `process` from within an action in the FSM.

**Comment by uyha** [comment] 2021-09-13 10:29
I tried calling `process` inside a function definition when trying to familiarize myself with the library. I don't think it's ever works as expected and it will only work when called inside `make_transition_table`.

**Comment by redboltz** [comment] 2021-09-13 12:10
@kris-jusiak ,I found a different behavior between windows and linux.

The crash is happened at 
https://github.com/boost-ext/sml/blob/a1c0603ea0e8ab6380c34d6dcdf0a075c6ecb5c2/include/boost/sml/back/queue_handler.hpp#L34

It seems that the `size` of `data` is invalid on only Windows.

The `size` is defined at
https://github.com/boost-ext/sml/blob/a1c0603ea0e8ab6380c34d6dcdf0a075c6ecb5c2/include/boost/sml/back/queue_handler.hpp#L19

I inserted size printing code as follows:

```cpp
  queue_event(queue_event &&other) : id(other.id), dtor(other.dtor), move(other.move) {
    std::cout << "size:" << size << std::endl;
    move(data, static_cast<queue_event &&>(other));
  }
```

On Linux, it is 32. The value is reflected the sizeof e2. But on Windows, it is always 8.
It caused the crash.

I don't know why it happened but it is a good start point to solve the issue.
Perhaps variadic templates related compiler bug exists.

**Comment by redboltz** [comment] 2021-09-13 12:23
On my following Windows environment, the problem is solved as follows:
Microsoft Visual Studio Community 2019
Version 16.11.2

The invalid `size` is caused by the following code:
https://github.com/boost-ext/sml/blob/a1c0603ea0e8ab6380c34d6dcdf0a075c6ecb5c2/include/boost/sml/aux_/utility.hpp#L274-L292

It seems that the following code is some workaround:

https://github.com/boost-ext/sml/blob/a1c0603ea0e8ab6380c34d6dcdf0a075c6ecb5c2/include/boost/sml/aux_/utility.hpp#L274-L285

I temporary modified the code as follows:

before
```cpp
#if defined(_MSC_VER) && !defined(__clang__)  // __pph__
```

after
```cpp
#if 0
```

Then

```cpp
constexpr int max_element() {
  int max = 0;
  (void)swallow{0, (Ts > max ? max = Ts : max)...};
  return max;
}
```

is used.

Then the `size` becomes valid value.

I don't know why MSVC workaround code is introduced. 
Perhaps the workaround code has bug.
At least my MSVC works well with the same `max_element()` code as Linux.

I think that `_MSC_VER` should be checked not only defined but also the value.
See https://stackoverflow.com/questions/70013/how-to-detect-if-im-compiling-code-with-a-particular-visual-studio-version/70630#70630

I'm not sure but if workaround code has bug, it should be fixed.

**Comment by redboltz** [comment] 2021-09-13 12:28
@uyha, @dingari 
posting process during a transition has two notations. One is direct notation in `make_transition_table` as @uyha mentioned. 
The other is function call style notation. It's more flexible. We can post event in application code. 
See https://github.com/boost-ext/sml/issues/144#issuecomment-581370339

The latter shouldn't be UB. It should work well.
In this case, just size calculation problem is sml.

**Comment by krzysztof-jusiak** [comment] 2021-09-13 12:50
Thanks @redboltz, good find, old MS version didn't support fold expressions well, that's why the wknd, but I think that can be cleaned up now, will create a MR with a fix, thanks :bowing_man:

**Comment by redboltz** [comment] 2021-09-13 12:57
I also found workaround code problem:

The following variadic non-template type parameter seems to be wrong.
```cpp
constexpr int max_element_impl(int r, int i, int ints...) {
  return i > r ? max_element_impl(i, ints) : max_element_impl(r, ints);
}
```

I replaced it with template as follows, then work as I expected:

```cpp
template <typename... Ts>
constexpr int max_element_impl(int r, int i, Ts... ints) {
  return i > r ? max_element_impl(i, ints...) : max_element_impl(r, ints...);
}
```

It is just a PoC code, so Ts can accpept any types but the caller limits it as int.

```cpp
template <int... Ts>
constexpr int max_element() {
  return max_element_impl(Ts...);
}
```

I think that it is good enough to older (maybe return only constexpr) MSVC.

Also I found that the multi-line constexpr has been supported since the following version:
https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements-2017?view=msvc-160

**Closed** 2021-09-15 13:33 UTC
